doctor:
    resource: ../../src/Core/Doctor/Controller/
    type: annotation
visit:
    resource: ../../src/Core/Visit/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
